#
# Copyright (C) 2024 nosignals
#
name: Building Neko DEVyt

on:
  push:
    branches:
      - main
    paths:
      - 'ocgen/Makefile'
  workflow_dispatch:
    inputs:
      version:
        description: 'Neko version'
        required: true
        default: '1.2.2-beta'
        type: string
      changelog:
        description: 'Changelog'
        required: true
        default: ''
        type: string
       
    
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build Neko
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.4
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      
      - name: Preparing Neko
        run: |
              echo ""
              git clone https://github.com/Houjie80/ocgen2
              mkdir feeds artifacts
              cp -rf ./ocgen ./feeds
        
      - name: Building luci-app-neko
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: ocgen
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: neko-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./artifact
          cp -rf ./neko-23.05.4_x86_64/* ./artifact/luci-app-ocgen_${{ inputs.version }}_dev_all.ipk
        
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/*
          overwrite: true
          prerelease: true
          tag: tes
          file_glob: true
          body: |
            # LUCI APP RAMFREE
            Simple Clash TUN based Proxy
            ### Information
            - Changelog : 
              - dev build, not recomended to install
              - ${{ inputs.changelog }}
            - Default Config : 
              - config.yaml : minimal Configs for Neko (only 1 rules) - Secret : ` sign `
              - nosignals.yaml : 2 rules can added (Block Host, Game) - Secret : ` telekulo `
            ### Dependency Requirement
            - ` bash, kmod-tun, php, php-cgi ` (install PHP Manually before install Neko)
            - Openwrt 23: ` php8 php8-cgi nftables mihomo` 
